version: '3'

services:
  neo4j:
    image: neo4j:4.2
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max_size=1G
  dataservice:
    container_name: 'dataproc-service'
    image: dataservice:1.0
    build:
        context: ./
    networks:
        kong:
    restart: unless-stopped
    ports:
        - "8055:8000"
    volumes:
        - dataproc-data:/code
    depends_on:
        - neo4j

volumes:
  dataproc-data:


networks:
  kong:
    external:
      name: kong_net
